/**
 * Regenerates AUTHORS from git history (needs a full clone, not a shallow one).
 * Everyone who authored a commit is listed, ordered by first contribution.
 */
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';

const log = execFileSync('git', ['log', '--reverse', '--format=%aN'], {
  encoding: 'utf8',
});

const names = [...new Set(log.split('\n').filter(Boolean))].filter(
  (name) => !name.endsWith('[bot]')
);

const header = `# Authors

Everyone who has contributed commits to this database, in order of first
contribution. Includes all contributors to the original
tombatossals/chords-db, from which this project is forked.

Generated by \`npm run authors\`; do not edit by hand.

`;

fs.writeFileSync('AUTHORS', header + names.map((n) => `- ${n}`).join('\n') + '\n');
console.log(`Wrote ${names.length} authors to AUTHORS`);
