/**
 * Validates every chord in data/ and writes reports/validation.md.
 *
 * Report-only for now: findings do not fail CI, but CI checks the report is
 * up to date, so every data fix shows up as a shrinking diff here.
 */
import fs from 'node:fs';
import path from 'node:path';
import { RULES, validateChord, type ValidationIssue } from '../src/validate';
import { loadInstruments, ROOT } from './data-source';

interface Finding extends ValidationIssue {
  instrument: string;
  chord: string;
  file: string;
}

const instruments = loadInstruments();
const findings: Finding[] = [];
let voicingCount = 0;

for (const { instrument, chords } of instruments) {
  for (const { chord, file } of chords) {
    voicingCount += chord.voicings.length;
    for (const issue of validateChord(instrument, chord).issues) {
      findings.push({ ...issue, instrument: instrument.id, chord: `${chord.key}${chord.suffix}`, file });
    }
  }
}

const ids = instruments.map((i) => i.instrument.id);
const voicingsWith = (severity: string) =>
  new Set(findings.filter((f) => f.severity === severity && f.voicingId).map((f) => f.voicingId)).size;
const rulesFound = Object.keys(RULES).filter((rule) => findings.some((f) => f.rule === rule));

const lines = [
  '# Validation report',
  '',
  'Generated by `npm run validate` from `data/`; do not edit by hand. The rules',
  'are defined in `src/validate.ts` and the chord formulas in',
  '`data/qualities.json`.',
  '',
  `- Voicings checked: ${voicingCount}`,
  `- Voicings with errors: ${voicingsWith('error')}`,
  `- Voicings with warnings only: ${
    new Set(
      findings
        .filter((f) => f.severity === 'warning' && f.voicingId)
        .map((f) => f.voicingId)
        .filter((id) => !findings.some((f) => f.severity === 'error' && f.voicingId === id))
    ).size
  }`,
  `- Chord-level findings: ${findings.filter((f) => !f.voicingId).length}`,
  '',
  '## Summary',
  '',
  `| Rule | Severity | ${ids.join(' | ')} | Total |`,
  `| --- | --- | ${ids.map(() => '---:').join(' | ')} | ---: |`,
  ...rulesFound.map((rule) => {
    const counts = ids.map((id) => findings.filter((f) => f.rule === rule && f.instrument === id).length);
    return `| [\`${rule}\`](#${rule.replace(/[^a-z0-9-]/g, '')}) | ${RULES[rule].severity} | ${counts.join(' | ')} | ${counts.reduce((a, b) => a + b, 0)} |`;
  }),
  '',
];

for (const rule of rulesFound) {
  lines.push(`## ${rule}`, '', `${RULES[rule].description} (${RULES[rule].severity})`, '');
  for (const id of ids) {
    const matching = findings.filter((f) => f.rule === rule && f.instrument === id);
    if (!matching.length) continue;
    lines.push(`### ${id} (${matching.length})`, '');
    for (const f of matching) {
      const what = f.voicingId ? `\`${f.voicingId}\`` : `**${f.chord}** (\`${f.file}\`)`;
      lines.push(`- ${what}: ${f.message}`);
    }
    lines.push('');
  }
}

fs.mkdirSync(path.join(ROOT, 'reports'), { recursive: true });
fs.writeFileSync(path.join(ROOT, 'reports', 'validation.md'), lines.join('\n'));
console.log(
  `${voicingCount} voicings: ${voicingsWith('error')} with errors, ${findings.length} findings. Wrote reports/validation.md`
);
